### ISSUE TITLE
Not working on El Capitan

### ISSUE THREAD

**Issue by highacid** [jimbojsb/launchrocket#63] opened 2016-02-23 02:28 UTC
Hello,

This is an amazing prefpane, would be glad to see it functional on El Capitan, any workaround?

**Comment by JustinAiken** [comment] 2016-02-23 02:29
Works on El Capitan for me..

**Comment by highacid** [comment] 2016-02-23 02:35
@JustinAiken I have brew installed and when I open the prefpane, I get this only: http://prntscr.com/a6s8ud my brew is up to date: 
$ brew update
Updated Homebrew from e13011d to e8a2f30.
Updated 1 tap (caskroom/cask).

**Comment by jimbojsb** [comment] 2016-02-23 14:29
do you have app signing security turned on?

**Comment by highacid** [comment] 2016-02-23 23:35
@jimbojsb No it is off.

**Comment by highacid** [comment] 2016-02-23 23:37
When I click the scan button I get this:

24/02/16 00:36:23,009 System Preferences[45865]: Found 'brew' at /usr/local/bin/brew, assuming that's the homebrew prefix
24/02/16 00:36:23,009 System Preferences[45865]: Scanning homebrew opt/
24/02/16 00:36:23,009 System Preferences[45865]: Scanning for special plists
24/02/16 00:36:23,010 System Preferences[45865]: Scanning for homebrew etc/launchrocket
24/02/16 00:36:23,010 System Preferences[45865]: Removing non-existent services from preferences
24/02/16 00:36:23,011 System Preferences[45865]: Wrote preferences file
24/02/16 00:36:23,011 System Preferences[45865]: Attempting to load services from plist
24/02/16 00:36:23,011 System Preferences[45865]: Successfully loaded services from plist
24/02/16 00:36:23,255 xpcproxy[45963]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
24/02/16 00:36:23,255 xpcproxy[45963]: LaunchServices: Database mapping failed with result -10822, retrying
24/02/16 00:36:23,255 xpcproxy[45963]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
24/02/16 00:36:23,259 xpcproxy[45963]: CFPreferences could not connect to its daemon.
 Preferences using the connection 0x0 will be volatile and will not be persisted to disk.
24/02/16 00:36:23,277 xpcproxy[45963]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
24/02/16 00:36:23,277 xpcproxy[45963]: LaunchServices: Database mapping failed with result -10822, retrying
24/02/16 00:36:23,278 xpcproxy[45963]: LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database
24/02/16 00:36:23,279 com.apple.xpc.launchd[1]: (com.uglyapps.HocusFocusHelper[45963]) Could not find and/or execute program specified by service: 155: Refusing to execute/trust quarantined program/file: com.uglyapps.HocusFocusHelper
24/02/16 00:36:23,280 com.apple.xpc.launchd[1]: (com.uglyapps.HocusFocusHelper) Service only ran for 0 seconds. Pushing respawn out by 10 seconds.


And then it repeats only the last part with XPC errors on and on.

**Comment by highacid** [comment] 2016-03-08 13:33
Any news on this? Still not working.

**Comment by jimbojsb** [comment] 2016-03-08 13:40
Sorry, I thought I had replied to this. LaunchRocket directly interacts with OSX Launchd. The step this is failing on is asking launchd  for the status of services (whether they are running or not). The error you have here has to do with your El Capitan upgrade, nothing to do with LaunchRocket. Most people report this issue if they had used an El Cap beta at some point and not done a clean install to the final version. The issue is related to some service being quarantined (com.uglyapps.HocusFocusHelper?). Google "LaunchServices: received XPC_ERROR_CONNECTION_INTERRUPTED trying to map database" and you'll see tons of information on the topic. Unfortunately, I have to close this issue as it is not LaunchRocket related at all :(

**Closed** 2016-03-08 13:40 UTC
